#include <iostream>
#include <fstream>
#include <drawer.hpp>

#include <

using namespace std;

// Variable

ifstream in("config.cfg");
ofstream out;

class dwr
{
    public: 
        struct 
        {

            // Default settings
            struct
            {

                string title_color = __shclr.text_black;
                string title_background = __shclr.bg_white;
                string context_color = __shclr.text_black;
                string context_background = __shclr.bg_white;
                
            } text;
            
            struct
            {
                
                string context_color = __shclr.text_white;
                string background_color = __shclr.bg_blue;
                string selected_background_color = __shclr.bg_black;
                string selected_color = __shclr.text_opposite;

            } input;
            
            struct
            {

                string context_color=__shclr.text_black;
                string context_background=__shclr.bg_white;
                string selected_background=__shclr.bg_blue;
                string selected_color=__shclr.text_white;

            } button;
            
        } __RES;

        ~dwr() {
            if(!in.is_open())
            {
                cerr << __shclr.text_yellow << "No config found! Will create one automatically.\n" << __shclr.clear;
                if(system("touch ./config.cfg")) 
                {
                    cerr << __shclr.text_red << "Failed to create profile! Will use default config.\n" << __shclr.clear;
                    goto untilf;
                }

                ofstream new_conf_("config.cfg");

                new_conf_ << "; This is an auto generate config file generated by Core.\n";
                new_conf_ << "; You could edit it for customize your Core TUI!\n";

                new_conf_ << "[Text]\n";
                new_conf_ << "title-color=black\n";
                new_conf_ << "title-background=white\n";
                new_conf_ << "context-color=black\n";
                new_conf_ << "context-background=white\n";

                new_conf_ << "\n";

                new_conf_ << "[Input]\n";
                new_conf_ << "context-color=white\n";
                new_conf_ << "background-color=blue\n";
                new_conf_ << "selected-background=black\n";
                new_conf_ << "selected-color=opposite:\n";

                new_conf_ << "\n";

                new_conf_ << "[Button]\n";
                new_conf_ << "context-color=black\n";
                new_conf_ << "context-background=white\n";
                new_conf_ << "selected-background=blue\n";
                new_conf_ << "selected-color=white\n";

                new_conf_ << "\n";

                new_conf_ << "; Will have more options in the future\n";
                new_conf_ << "; Stay tuned!\n";
            }
        untilf:
            if (in.is_open())
                in.close();
            in.clear();
            in.open("config.cfg");

            string class_ = "";
            string section = "";
            bool oppoback = "";
            while (getline(in, class_))
            {
                if (!class_.empty() && class_.back() == '\r')
                    class_.pop_back();
                if (class_.empty() || class_[0] == ';')
                    continue;

                if (class_[0] == '[' && class_.back() == ']')
                {
                    section = class_;
                    continue;
                }

                if (section != "[Text]")
                    continue;

                const size_t separator = class_.find('=');
                if (separator == string::npos)
                    cerr << __shclr.text_yellow << "Cannot read \"" << class_ << "\"!\n";

                const string key = class_.substr(0, separator);
                const string color = class_.substr(separator + 1);

                if (key == "title-color")
                {

                    string __TMP;

                    if (color == "black") __TMP=__shclr.text_black;
                    else if (color == "white") __TMP=__shclr.text_white;
                    else if (color == "yellow") __TMP=__shclr.text_yellow;
                    else if (color == "green") __TMP=__shclr.text_green;
                    else if (color == "cyan") __TMP=__shclr.text_cyan;
                    else if (color == "red") __TMP=__shclr.text_red;
                    else if (color == "blue") __TMP=__shclr.text_blue;
                    else if (color == "magenta") __TMP=__shclr.text_magenta;
                    else if (color.find("opposite") != string::npos)
                        __TMP=__shclr.text_opposite;

                    __RES.text.title_color=__TMP;
                        
                }
                else if (key == "title-background")
                {

                    string __TMP;

                    if (color == "black") __TMP=__shclr.bg_black;
                    else if (color == "white") __TMP=__shclr.bg_white;
                    else if (color == "yellow") __TMP=__shclr.bg_yellow;
                    else if (color == "green") __TMP=__shclr.bg_green;
                    else if (color == "cyan") __TMP=__shclr.bg_cyan;
                    else if (color == "red") __TMP=__shclr.bg_red;
                    else if (color == "blue") __TMP=__shclr.bg_blue;
                    else if (color == "magenta") __TMP=__shclr.bg_magenta;
                    else if (color.find("opposite") != string::npos)
                        __TMP=__shclr.text_opposite;

                    __RES.text.title_background=__TMP;

                }
                else if (key == "context-color")
                {

                    string __TMP;

                    if (color == "black") __TMP=__shclr.text_black;
                    else if (color == "white") __TMP=__shclr.text_white;
                    else if (color == "yellow") __TMP=__shclr.text_yellow;
                    else if (color == "green") __TMP=__shclr.text_green;
                    else if (color == "cyan") __TMP=__shclr.text_cyan;
                    else if (color == "red") __TMP=__shclr.text_red;
                    else if (color == "blue") __TMP=__shclr.text_blue;
                    else if (color == "magenta") __TMP=__shclr.text_magenta;
                    else if (color.find("opposite") != string::npos)
                        __TMP=__shclr.text_opposite;

                    __RES.text.title_color=__TMP;

                }
                else if (key == "context-background")
                {

                    string __TMP;

                    if (color == "black") __TMP=__shclr.bg_black;
                    else if (color == "white") __TMP=__shclr.bg_white;
                    else if (color == "yellow") __TMP=__shclr.bg_yellow;
                    else if (color == "green") __TMP=__shclr.bg_green;
                    else if (color == "cyan") __TMP=__shclr.bg_cyan;
                    else if (color == "red") __TMP=__shclr.bg_red;
                    else if (color == "blue") __TMP=__shclr.bg_blue;
                    else if (color == "magenta") __TMP=__shclr.bg_magenta;
                    else if (color.find("opposite") != string::npos)
                        __TMP=__shclr.text_opposite;

                    __RES.text.title_background=__TMP;
                    
                }
            }
        }

};