#include <iostream>
#include <fstream>
using namespace std;

// Const value

// Color

const string BG_BLACK="\e[40m";   // 黑色
const string BG_RED="\e[41m";     // 红色
const string BG_GREEN="\e[42m";   // 绿色
const string BG_YELLOW="\e[43m";  // 黄色
const string BG_BLUE="\e[44m";    // 蓝色
const string BG_MAGENTA="\e[45m"; // 紫色
const string BG_CYAN="\e[46m";    // 青色
const string BG_WHITE="\e[47m";   // 白色

const string BG_BRIGHT_BLACK="\e[100m";   // 稍亮的黑色
const string BG_BRIGHT_RED="\e[101m";     // 亮红色
const string BG_BRIGHT_GREEN="\e[102m";   // 浅绿色
const string BG_BRIGHT_YELLOW="\e[103m";  // 亮黄色
const string BG_BRIGHT_BLUE="\e[104m";    // 亮蓝色
const string BG_BRIGHT_MAGENTA="\e[105m"; // 亮紫色
const string BG_BRIGHT_CYAN="\e[106m";    // 亮青色
const string BG_BRIGHT_WHITE="\e[107m";   // 亮白色

// 前景色（文本色）
const string TEXT_BLACK="\x1B[30;1m";  // 黑色
const string TEXT_WHITE="\x1B[37;1m";  // 白色
const string TEXT_YELLOW="\x1B[33;1m"; // 黄色
const string TEXT_GREEN="\x1B[32;1m";  // 绿色
const string TEXT_CYAN="\x1B[36;1m";   // 青色
const string TEXT_RED="\x1B[31;1m";    // 红色
const string TEXT_BLUE="\x1B[34;1m";   // 蓝色
const string TEXT_MAGENTA="\x1B[35;1m"; // 紫色

// 字体样式
const string TEXT_UL="\x1B[4m";     // 下划线
const string TEXT_BOLD="\x1B[1m";   // 加粗
const string TEXT_BLINK="\x1B[5m";  // 闪烁
const string TEXT_INVERT="\x1B[7m"; // 反转
const string TEXT_DISAPP="\x1B[8m"; // 消失

// 清空当前层效果

const string NC="\x1B[0m";


// Variable

ifstream in("config.cfg");
ofstream out;


class dwr
{
    public: 
        ~dwr() {
            if(!in.is_open())
            {
                cerr << TEXT_YELLOW << "No config found! Will create one automatically.\n" << NC;
                if(system("touch ./config.cfg")) 
                {
                    cerr << TEXT_RED << "Failed to create profile! Will use default config.\n" << NC;
                    goto untilf;
                }

                ofstream new_conf_("config.cfg");

                new_conf_ << "; This is an auto generate config file generated by Core.\n";
                new_conf_ << "; You could edit it for customize your Core TUI!\n";

                new_conf_ << "[Text]\n";
                new_conf_ << "title-color=black\n";
                new_conf_ << "title-background=white\n";
                new_conf_ << "context-color=black\n";
                new_conf_ << "context-background=white\n";

                new_conf_ << "\n";

                new_conf_ << "[Input]\n";
                new_conf_ << "context-color=white\n";
                new_conf_ << "background-color=blue\n";
                new_conf_ << "selected-background=black\n";
                new_conf_ << "selected-color=opposite:\n";

                new_conf_ << "\n";

                new_conf_ << "[Button]\n";
                new_conf_ << "context-color=black\n";
                new_conf_ << "context-background=white\n";
                new_conf_ << "selected-background=blue\n";
                new_conf_ << "selected-color=white\n";

                new_conf_ << "\n";

                new_conf_ << "; Will have more options in the future\n";
                new_conf_ << "; Stay tuned!\n";
            }
        untilf:
            string class_ = "";
            int cfgline = 1;
            while(getline(in, class_) || class_ != "") 
            {
                if(class_ == "[Text]") 
                {
                    while(getline(in, class_) && class_ != "") 
                    {
                        if(class_.find("title-color") != string::npos) 
                        {
                            string color = class_.substr(class_.find("=") + 1);
                            if(color == "black") cout << TEXT_BLACK;
                            else if(color == "white") cout << TEXT_WHITE;
                            else if(color == "yellow") cout << TEXT_YELLOW;
                            else if(color == "green") cout << TEXT_GREEN;
                            else if(color == "cyan") cout << TEXT_CYAN;
                            else if(color == "red") cout << TEXT_RED;
                            else if(color == "blue") cout << TEXT_BLUE;
                            else if(color == "magenta") cout << TEXT_MAGENTA;
                            else if(color.find("opposite") != string::npos) 
                                cerr << "\"opposite\" tag cannot use at text. If you want to use it to get the background color's opposite color, please use \"oppoback\" instead.\n"
                        }
                        else if(class_.find("title-background") != string::npos) 
                        {
                            string color = class_.substr(class_.find("=") + 1);
                            if(color == "black") cout << BG_BLACK;
                            else if(color == "white") cout << BG_WHITE;
                            else if(color == "yellow") cout << BG_YELLOW;
                            else if(color == "green") cout << BG_GREEN;
                            else if(color == "cyan") cout << BG_CYAN;
                            else if(color == "red") cout << BG_RED;
                            else if(color == "blue") cout << BG_BLUE;
                            else if(color == "magenta") cout << BG_MAGENTA;
                        }
                        cfgline++;
                    }
                }
                class_ = "";
                cfgline++;
            }
        }

};